{
    "patcher": {
        "fileversion": 1,
        "appversion": {
            "major": 8,
            "minor": 6,
            "revision": 5,
            "architecture": "x64",
            "modernui": 1
        },
        "classnamespace": "box",
        "rect": [80.0, 80.0, 1400.0, 820.0],
        "bglocked": 0,
        "openinpresentation": 1,
        "devicewidth": 1080.0,
        "default_fontsize": 12.0,
        "default_fontface": 0,
        "default_fontname": "Arial",
        "gridonopen": 1,
        "gridsize": [15.0, 15.0],
        "gridsnaponopen": 1,
        "objectsnaponopen": 1,
        "statusbarvisible": 2,
        "toolbarvisible": 1,
        "boxes": [
            {"box": {"id": "obj-header", "maxclass": "comment", "text": "Oedipa — Tonnetz chord walker", "numinlets": 1, "numoutlets": 0, "fontsize": 14.0, "patching_rect": [40.0, 10.0, 240.0, 22.0]}},

            {"box": {"id": "obj-midiin", "maxclass": "newobj", "text": "midiin", "numinlets": 1, "numoutlets": 1, "outlettype": ["int"], "patching_rect": [40.0, 60.0, 45.0, 22.0]}},
            {"box": {"id": "obj-midiout", "maxclass": "newobj", "text": "midiout", "numinlets": 1, "numoutlets": 0, "patching_rect": [40.0, 720.0, 52.0, 22.0]}},

            {"box": {"id": "obj-midiparse", "maxclass": "newobj", "text": "midiparse", "numinlets": 1, "numoutlets": 7, "outlettype": ["", "", "", "int", "int", "int", "int"], "patching_rect": [40.0, 100.0, 80.0, 22.0]}},
            {"box": {"id": "obj-unpack-note-in", "maxclass": "newobj", "text": "unpack 0 0", "numinlets": 1, "numoutlets": 2, "outlettype": ["int", "int"], "patching_rect": [40.0, 130.0, 80.0, 22.0]}},
            {"box": {"id": "obj-if-noteinout", "maxclass": "newobj", "text": "if $i2 > 0 then noteIn $i1 $i2 $i3 else noteOff $i1 $i3", "numinlets": 3, "numoutlets": 1, "outlettype": [""], "patching_rect": [40.0, 190.0, 380.0, 22.0]}},

            {"box": {"id": "obj-thisdevice", "maxclass": "newobj", "text": "live.thisdevice", "numinlets": 1, "numoutlets": 3, "outlettype": ["bang", "bang", ""], "patching_rect": [130.0, 60.0, 102.0, 22.0]}},
            {"box": {"id": "obj-print-thisdev", "maxclass": "newobj", "text": "print thisdev", "numinlets": 1, "numoutlets": 0, "patching_rect": [240.0, 60.0, 85.0, 22.0]}},
            {"box": {"id": "obj-loadbang", "maxclass": "newobj", "text": "loadbang", "numinlets": 1, "numoutlets": 1, "outlettype": ["bang"], "patching_rect": [130.0, 90.0, 65.0, 22.0]}},
            {"box": {"id": "obj-debug-bang", "maxclass": "button", "numinlets": 1, "numoutlets": 1, "outlettype": ["bang"], "patching_rect": [210.0, 90.0, 24.0, 24.0]}},
            {"box": {"id": "obj-debug-comment", "maxclass": "comment", "text": "manual re-resolve (debug)", "numinlets": 1, "numoutlets": 0, "patching_rect": [240.0, 92.0, 170.0, 20.0]}},

            {"box": {"id": "obj-getid-msg", "maxclass": "message", "text": "getid", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [130.0, 130.0, 46.0, 22.0]}},
            {"box": {"id": "obj-livepath", "maxclass": "newobj", "text": "live.path live_set", "numinlets": 1, "numoutlets": 3, "outlettype": ["", "", ""], "patching_rect": [130.0, 170.0, 115.0, 22.0]}},
            {"box": {"id": "obj-print-lp", "maxclass": "newobj", "text": "print lp", "numinlets": 1, "numoutlets": 0, "patching_rect": [260.0, 170.0, 60.0, 22.0]}},

            {"box": {"id": "obj-liveobserver", "maxclass": "newobj", "text": "live.observer is_playing", "numinlets": 2, "numoutlets": 3, "outlettype": ["", "", ""], "patching_rect": [130.0, 210.0, 160.0, 22.0]}},
            {"box": {"id": "obj-print-lo", "maxclass": "newobj", "text": "print lo", "numinlets": 1, "numoutlets": 0, "patching_rect": [310.0, 210.0, 60.0, 22.0]}},

            {"box": {"id": "obj-sel-stop", "maxclass": "newobj", "text": "sel 0 1", "numinlets": 1, "numoutlets": 3, "outlettype": ["bang", "bang", ""], "patching_rect": [130.0, 250.0, 50.0, 22.0]}},
            {"box": {"id": "obj-msg-transportstart", "maxclass": "message", "text": "transportStart", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [200.0, 250.0, 110.0, 22.0]}},

            {"box": {"id": "obj-test-bang", "maxclass": "button", "numinlets": 1, "numoutlets": 1, "outlettype": ["bang"], "patching_rect": [480.0, 60.0, 24.0, 24.0]}},
            {"box": {"id": "obj-test-comment", "maxclass": "comment", "text": "manual step (test)", "numinlets": 1, "numoutlets": 0, "patching_rect": [510.0, 62.0, 130.0, 20.0]}},
            {"box": {"id": "obj-metro", "maxclass": "newobj", "text": "metro 96n @quantize 96n @active 0", "numinlets": 2, "numoutlets": 1, "outlettype": ["bang"], "patching_rect": [480.0, 250.0, 220.0, 22.0]}},
            {"box": {"id": "obj-print-metro", "maxclass": "newobj", "text": "print metro", "numinlets": 1, "numoutlets": 0, "patching_rect": [710.0, 250.0, 80.0, 22.0]}},
            {"box": {"id": "obj-metro-comment", "maxclass": "comment", "text": "Live transport sync", "numinlets": 1, "numoutlets": 0, "patching_rect": [800.0, 252.0, 140.0, 20.0]}},
            {"box": {"id": "obj-counter", "maxclass": "newobj", "text": "counter", "numinlets": 5, "numoutlets": 4, "outlettype": ["int", "int", "int", "int"], "patching_rect": [480.0, 290.0, 55.0, 22.0]}},
            {"box": {"id": "obj-prepend-step", "maxclass": "newobj", "text": "prepend step", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [480.0, 330.0, 85.0, 22.0]}},

            {"box": {"id": "obj-panic-bang", "maxclass": "button", "numinlets": 1, "numoutlets": 1, "outlettype": ["bang"], "patching_rect": [770.0, 60.0, 24.0, 24.0]}},
            {"box": {"id": "obj-panic-comment", "maxclass": "comment", "text": "panic (all notes off)", "numinlets": 1, "numoutlets": 0, "patching_rect": [800.0, 62.0, 140.0, 20.0]}},
            {"box": {"id": "obj-panic-msg", "maxclass": "message", "text": "panic", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [770.0, 110.0, 46.0, 22.0]}},

            {"box": {"id": "obj-nodescript", "maxclass": "newobj", "text": "node.script /Users/tn/src/vst/oedipa/m4l/host/index.js @autostart 1", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [130.0, 390.0, 420.0, 22.0]}},

            {"box": {"id": "obj-print", "maxclass": "newobj", "text": "print from_node", "numinlets": 1, "numoutlets": 0, "patching_rect": [130.0, 440.0, 105.0, 22.0]}},

            {"box": {"id": "obj-route", "maxclass": "newobj", "text": "route note", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [480.0, 440.0, 75.0, 22.0]}},
            {"box": {"id": "obj-unpack", "maxclass": "newobj", "text": "unpack 0 0 0", "numinlets": 1, "numoutlets": 3, "outlettype": ["int", "int", "int"], "patching_rect": [480.0, 500.0, 80.0, 22.0]}},
            {"box": {"id": "obj-pack", "maxclass": "newobj", "text": "pack 0 0", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [480.0, 560.0, 60.0, 22.0]}},
            {"box": {"id": "obj-midiformat", "maxclass": "newobj", "text": "midiformat", "numinlets": 2, "numoutlets": 1, "outlettype": ["int"], "patching_rect": [480.0, 620.0, 70.0, 22.0]}},

            {"box": {"id": "obj-params-comment", "maxclass": "comment", "text": "Parameters (Group A + B)", "numinlets": 1, "numoutlets": 0, "fontsize": 12.0, "patching_rect": [970.0, 60.0, 200.0, 22.0]}},

            {"box": {"id": "obj-panel-controls", "maxclass": "panel", "bgcolor": [0, 0, 0, 0], "bordercolor": [0.4, 0.4, 0.4, 1], "border": 0, "rounded": 4, "patching_rect": [970.0, 50.0, 144.0, 180.0], "presentation": 0}},

            {"box": {"id": "obj-jsui-separator", "maxclass": "jsui", "filename": "/Users/tn/src/vst/oedipa/m4l/separator-renderer.js", "border": 0, "numinlets": 1, "numoutlets": 0, "patching_rect": [970.0, 240.0, 1.0, 172.0], "presentation": 1, "presentation_rect": [477.0, 8.0, 1.0, 172.0]}},

            {"box": {"id": "obj-stepsper", "maxclass": "live.numbox", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [970.0, 90.0, 60.0, 22.0], "presentation": 1, "presentation_rect": [486.0, 24.0, 50.0, 18.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [4], "parameter_initial_enable": 1, "parameter_longname": "OedipaSteps", "parameter_mmax": 32.0, "parameter_mmin": 1.0, "parameter_shortname": "Steps", "parameter_type": 1, "parameter_unitstyle": 0}}}},
            {"box": {"id": "obj-prep-stepsper", "maxclass": "newobj", "text": "prepend setParams stepsPerTransform", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1100.0, 90.0, 220.0, 22.0]}},
            {"box": {"id": "obj-lbl-stepsper", "maxclass": "comment", "text": "Steps", "numinlets": 1, "numoutlets": 0, "fontsize": 9.0, "patching_rect": [1300.0, 90.0, 60.0, 16.0], "presentation": 1, "presentation_rect": [486.0, 8.0, 50.0, 14.0]}},

            {"box": {"id": "obj-seventh", "maxclass": "live.toggle", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [970.0, 130.0, 24.0, 24.0], "presentation": 1, "presentation_rect": [540.0, 64.0, 18.0, 18.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [0], "parameter_initial_enable": 1, "parameter_longname": "OedipaSeventh", "parameter_mmax": 1.0, "parameter_mmin": 0.0, "parameter_shortname": "7th", "parameter_type": 1, "parameter_unitstyle": 0}}}},
            {"box": {"id": "obj-msg-getvalueof-seventh", "maxclass": "message", "text": "getvalueof", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [870.0, 130.0, 80.0, 22.0]}},
            {"box": {"id": "obj-prep-seventh", "maxclass": "newobj", "text": "prepend setParams seventh", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1100.0, 130.0, 170.0, 22.0]}},
            {"box": {"id": "obj-lbl-seventh", "maxclass": "comment", "text": "7th", "numinlets": 1, "numoutlets": 0, "fontsize": 9.0, "patching_rect": [1300.0, 130.0, 40.0, 16.0], "presentation": 1, "presentation_rect": [540.0, 48.0, 30.0, 14.0]}},

            {"box": {"id": "obj-channel", "maxclass": "live.numbox", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [970.0, 230.0, 60.0, 22.0], "presentation": 1, "presentation_rect": [486.0, 104.0, 50.0, 18.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [1], "parameter_initial_enable": 1, "parameter_longname": "OedipaChannel", "parameter_mmax": 16.0, "parameter_mmin": 1.0, "parameter_shortname": "Out Ch", "parameter_type": 1, "parameter_unitstyle": 0}}}},
            {"box": {"id": "obj-prep-channel", "maxclass": "newobj", "text": "prepend setParams channel", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1100.0, 230.0, 170.0, 22.0]}},
            {"box": {"id": "obj-lbl-channel", "maxclass": "comment", "text": "Out Ch", "numinlets": 1, "numoutlets": 0, "fontsize": 9.0, "patching_rect": [1300.0, 230.0, 50.0, 16.0], "presentation": 1, "presentation_rect": [486.0, 88.0, 50.0, 14.0]}},

            {"box": {"id": "obj-triggermode", "maxclass": "live.toggle", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [970.0, 810.0, 24.0, 24.0], "presentation": 1, "presentation_rect": [540.0, 24.0, 18.0, 18.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [0], "parameter_initial_enable": 1, "parameter_longname": "OedipaTriggerMode", "parameter_mmax": 1.0, "parameter_mmin": 0.0, "parameter_shortname": "Trig", "parameter_type": 1, "parameter_unitstyle": 0}}}},
            {"box": {"id": "obj-msg-getvalueof-trig", "maxclass": "message", "text": "getvalueof", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [870.0, 810.0, 80.0, 22.0]}},
            {"box": {"id": "obj-prep-triggermode", "maxclass": "newobj", "text": "prepend setParams triggerMode", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1100.0, 810.0, 220.0, 22.0]}},
            {"box": {"id": "obj-lbl-triggermode", "maxclass": "comment", "text": "Trig", "numinlets": 1, "numoutlets": 0, "fontsize": 9.0, "patching_rect": [1340.0, 810.0, 60.0, 16.0], "presentation": 1, "presentation_rect": [540.0, 8.0, 50.0, 14.0]}},

            {"box": {"id": "obj-inputchannel", "maxclass": "live.numbox", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [970.0, 850.0, 60.0, 22.0], "presentation": 1, "presentation_rect": [486.0, 64.0, 50.0, 18.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [0], "parameter_initial_enable": 1, "parameter_longname": "OedipaInputChannel", "parameter_mmax": 16.0, "parameter_mmin": 0.0, "parameter_shortname": "In Ch", "parameter_type": 1, "parameter_unitstyle": 0}}}},
            {"box": {"id": "obj-prep-inputchannel", "maxclass": "newobj", "text": "prepend setParams inputChannel", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1100.0, 850.0, 240.0, 22.0]}},
            {"box": {"id": "obj-lbl-inputchannel", "maxclass": "comment", "text": "In Ch", "numinlets": 1, "numoutlets": 0, "fontsize": 9.0, "patching_rect": [1360.0, 850.0, 60.0, 16.0], "presentation": 1, "presentation_rect": [486.0, 48.0, 50.0, 14.0]}},

            {"box": {"id": "obj-voicing", "maxclass": "live.tab", "numinlets": 1, "numoutlets": 3, "outlettype": ["", "", "float"], "parameter_enable": 1, "patching_rect": [970.0, 270.0, 130.0, 22.0], "presentation": 1, "presentation_rect": [486.0, 144.0, 122.0, 18.0], "saved_attribute_attributes": {"valueof": {"parameter_enum": ["Close", "Spread", "Drop 2"], "parameter_initial": [0], "parameter_initial_enable": 1, "parameter_longname": "OedipaVoicing", "parameter_shortname": "Voicing", "parameter_type": 2}}}},
            {"box": {"id": "obj-sel-voicing", "maxclass": "newobj", "text": "sel 0 1 2", "numinlets": 1, "numoutlets": 4, "outlettype": ["bang", "bang", "bang", ""], "patching_rect": [1100.0, 270.0, 70.0, 22.0]}},
            {"box": {"id": "obj-msg-voicing-close", "maxclass": "message", "text": "setParams voicing close", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1100.0, 300.0, 160.0, 22.0]}},
            {"box": {"id": "obj-msg-voicing-spread", "maxclass": "message", "text": "setParams voicing spread", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1100.0, 330.0, 170.0, 22.0]}},
            {"box": {"id": "obj-msg-voicing-drop2", "maxclass": "message", "text": "setParams voicing drop2", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1100.0, 360.0, 170.0, 22.0]}},
            {"box": {"id": "obj-lbl-voicing", "maxclass": "comment", "text": "Voicing", "numinlets": 1, "numoutlets": 0, "fontsize": 9.0, "patching_rect": [1300.0, 270.0, 60.0, 16.0], "presentation": 1, "presentation_rect": [486.0, 128.0, 60.0, 14.0]}},

            {"box": {"id": "obj-jsui-separator2", "maxclass": "jsui", "filename": "/Users/tn/src/vst/oedipa/m4l/separator-renderer.js", "border": 0, "numinlets": 1, "numoutlets": 0, "patching_rect": [970.0, 410.0, 1.0, 172.0], "presentation": 1, "presentation_rect": [617.0, 8.0, 1.0, 172.0]}},

            {"box": {"id": "obj-lbl-cells", "maxclass": "comment", "text": "Cells", "numinlets": 1, "numoutlets": 0, "fontsize": 9.0, "patching_rect": [1620.0, 410.0, 60.0, 16.0], "presentation": 1, "presentation_rect": [626.0, 8.0, 60.0, 14.0]}},

            {"box": {"id": "obj-cell0", "maxclass": "live.tab", "numinlets": 1, "numoutlets": 3, "outlettype": ["", "", "float"], "parameter_enable": 1, "patching_rect": [970.0, 440.0, 130.0, 22.0], "presentation": 1, "presentation_rect": [626.0, 32.0, 110.0, 18.0], "saved_attribute_attributes": {"valueof": {"parameter_enum": ["P", "L", "R", "—", "·"], "parameter_initial": [0], "parameter_initial_enable": 1, "parameter_longname": "OedipaCell0", "parameter_shortname": "Cell0", "parameter_type": 2}}}},
            {"box": {"id": "obj-sel-cell0", "maxclass": "newobj", "text": "sel 0 1 2 3 4", "numinlets": 1, "numoutlets": 6, "outlettype": ["bang", "bang", "bang", "bang", "bang", ""], "patching_rect": [1110.0, 440.0, 80.0, 22.0]}},
            {"box": {"id": "obj-msg-cell0-P", "maxclass": "message", "text": "setCell 0 P", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1110.0, 470.0, 100.0, 22.0]}},
            {"box": {"id": "obj-msg-cell0-L", "maxclass": "message", "text": "setCell 0 L", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1220.0, 470.0, 100.0, 22.0]}},
            {"box": {"id": "obj-msg-cell0-R", "maxclass": "message", "text": "setCell 0 R", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1330.0, 470.0, 100.0, 22.0]}},
            {"box": {"id": "obj-msg-cell0-H", "maxclass": "message", "text": "setCell 0 hold", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1440.0, 470.0, 110.0, 22.0]}},

            {"box": {"id": "obj-cell1", "maxclass": "live.tab", "numinlets": 1, "numoutlets": 3, "outlettype": ["", "", "float"], "parameter_enable": 1, "patching_rect": [970.0, 510.0, 130.0, 22.0], "presentation": 1, "presentation_rect": [750.0, 32.0, 110.0, 18.0], "saved_attribute_attributes": {"valueof": {"parameter_enum": ["P", "L", "R", "—", "·"], "parameter_initial": [1], "parameter_initial_enable": 1, "parameter_longname": "OedipaCell1", "parameter_shortname": "Cell1", "parameter_type": 2}}}},
            {"box": {"id": "obj-sel-cell1", "maxclass": "newobj", "text": "sel 0 1 2 3 4", "numinlets": 1, "numoutlets": 6, "outlettype": ["bang", "bang", "bang", "bang", "bang", ""], "patching_rect": [1110.0, 510.0, 80.0, 22.0]}},
            {"box": {"id": "obj-msg-cell1-P", "maxclass": "message", "text": "setCell 1 P", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1110.0, 540.0, 100.0, 22.0]}},
            {"box": {"id": "obj-msg-cell1-L", "maxclass": "message", "text": "setCell 1 L", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1220.0, 540.0, 100.0, 22.0]}},
            {"box": {"id": "obj-msg-cell1-R", "maxclass": "message", "text": "setCell 1 R", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1330.0, 540.0, 100.0, 22.0]}},
            {"box": {"id": "obj-msg-cell1-H", "maxclass": "message", "text": "setCell 1 hold", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1440.0, 540.0, 110.0, 22.0]}},

            {"box": {"id": "obj-cell2", "maxclass": "live.tab", "numinlets": 1, "numoutlets": 3, "outlettype": ["", "", "float"], "parameter_enable": 1, "patching_rect": [970.0, 580.0, 130.0, 22.0], "presentation": 1, "presentation_rect": [626.0, 62.0, 110.0, 18.0], "saved_attribute_attributes": {"valueof": {"parameter_enum": ["P", "L", "R", "—", "·"], "parameter_initial": [2], "parameter_initial_enable": 1, "parameter_longname": "OedipaCell2", "parameter_shortname": "Cell2", "parameter_type": 2}}}},
            {"box": {"id": "obj-sel-cell2", "maxclass": "newobj", "text": "sel 0 1 2 3 4", "numinlets": 1, "numoutlets": 6, "outlettype": ["bang", "bang", "bang", "bang", "bang", ""], "patching_rect": [1110.0, 580.0, 80.0, 22.0]}},
            {"box": {"id": "obj-msg-cell2-P", "maxclass": "message", "text": "setCell 2 P", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1110.0, 610.0, 100.0, 22.0]}},
            {"box": {"id": "obj-msg-cell2-L", "maxclass": "message", "text": "setCell 2 L", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1220.0, 610.0, 100.0, 22.0]}},
            {"box": {"id": "obj-msg-cell2-R", "maxclass": "message", "text": "setCell 2 R", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1330.0, 610.0, 100.0, 22.0]}},
            {"box": {"id": "obj-msg-cell2-H", "maxclass": "message", "text": "setCell 2 hold", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1440.0, 610.0, 110.0, 22.0]}},

            {"box": {"id": "obj-cell3", "maxclass": "live.tab", "numinlets": 1, "numoutlets": 3, "outlettype": ["", "", "float"], "parameter_enable": 1, "patching_rect": [970.0, 650.0, 130.0, 22.0], "presentation": 1, "presentation_rect": [750.0, 62.0, 110.0, 18.0], "saved_attribute_attributes": {"valueof": {"parameter_enum": ["P", "L", "R", "—", "·"], "parameter_initial": [3], "parameter_initial_enable": 1, "parameter_longname": "OedipaCell3", "parameter_shortname": "Cell3", "parameter_type": 2}}}},
            {"box": {"id": "obj-sel-cell3", "maxclass": "newobj", "text": "sel 0 1 2 3 4", "numinlets": 1, "numoutlets": 6, "outlettype": ["bang", "bang", "bang", "bang", "bang", ""], "patching_rect": [1110.0, 650.0, 80.0, 22.0]}},
            {"box": {"id": "obj-msg-cell3-P", "maxclass": "message", "text": "setCell 3 P", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1110.0, 680.0, 100.0, 22.0]}},
            {"box": {"id": "obj-msg-cell3-L", "maxclass": "message", "text": "setCell 3 L", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1220.0, 680.0, 100.0, 22.0]}},
            {"box": {"id": "obj-msg-cell3-R", "maxclass": "message", "text": "setCell 3 R", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1330.0, 680.0, 100.0, 22.0]}},
            {"box": {"id": "obj-msg-cell3-H", "maxclass": "message", "text": "setCell 3 hold", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1440.0, 680.0, 110.0, 22.0]}},

            {"box": {"id": "obj-jitter", "maxclass": "live.dial", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [970.0, 720.0, 60.0, 40.0], "presentation": 1, "presentation_rect": [626.0, 88.0, 50.0, 40.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [0.0], "parameter_initial_enable": 1, "parameter_longname": "OedipaJitter", "parameter_mmax": 1.0, "parameter_mmin": 0.0, "parameter_shortname": "Jitter", "parameter_type": 0, "parameter_unitstyle": 1}}}},
            {"box": {"id": "obj-prep-jitter", "maxclass": "newobj", "text": "prepend setParams jitter", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1100.0, 720.0, 170.0, 22.0]}},

            {"box": {"id": "obj-lbl-seed", "maxclass": "comment", "text": "Seed", "numinlets": 1, "numoutlets": 0, "fontsize": 9.0, "patching_rect": [1620.0, 770.0, 60.0, 16.0], "presentation": 1, "presentation_rect": [746.0, 84.0, 50.0, 14.0]}},
            {"box": {"id": "obj-seed", "maxclass": "live.numbox", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [970.0, 770.0, 60.0, 22.0], "presentation": 1, "presentation_rect": [746.0, 108.0, 90.0, 18.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [0.0], "parameter_initial_enable": 1, "parameter_longname": "OedipaSeed", "parameter_mmax": 99999.0, "parameter_mmin": 0.0, "parameter_shortname": "Seed", "parameter_steps": 100000, "parameter_type": 0, "parameter_unitstyle": 0}}}},
            {"box": {"id": "obj-prep-seed", "maxclass": "newobj", "text": "prepend setParams seed", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1100.0, 770.0, 170.0, 22.0]}},

            {"box": {"id": "obj-lattice-comment", "maxclass": "comment", "text": "Lattice (jsui)", "numinlets": 1, "numoutlets": 0, "fontsize": 12.0, "patching_rect": [130.0, 470.0, 130.0, 22.0]}},

            {"box": {"id": "obj-route-lattice", "maxclass": "newobj", "text": "route lattice-center lattice-current lattice-clear", "numinlets": 1, "numoutlets": 4, "outlettype": ["", "", "bang", ""], "patching_rect": [130.0, 500.0, 320.0, 22.0]}},
            {"box": {"id": "obj-prep-lcenter", "maxclass": "newobj", "text": "prepend latticeCenter", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [130.0, 530.0, 140.0, 22.0]}},
            {"box": {"id": "obj-prep-lcurrent", "maxclass": "newobj", "text": "prepend latticeCurrent", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [280.0, 530.0, 150.0, 22.0]}},
            {"box": {"id": "obj-msg-lclear", "maxclass": "message", "text": "latticeClear", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [440.0, 530.0, 90.0, 22.0]}},

            {"box": {"id": "obj-msg-refresh", "maxclass": "message", "text": "latticeRefresh", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [330.0, 130.0, 100.0, 22.0]}},

            {"box": {"id": "obj-jsui", "maxclass": "jsui", "filename": "/Users/tn/src/vst/oedipa/m4l/lattice-renderer.js", "border": 0, "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [130.0, 570.0, 460.0, 160.0], "presentation": 1, "presentation_rect": [8.0, 8.0, 460.0, 160.0]}},

            {"box": {"id": "obj-route-startchord", "maxclass": "newobj", "text": "route setStartChord", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [600.0, 410.0, 150.0, 22.0]}},
            {"box": {"id": "obj-unpack-sc", "maxclass": "newobj", "text": "unpack 0 0 0", "numinlets": 1, "numoutlets": 3, "outlettype": ["int", "int", "int"], "patching_rect": [600.0, 440.0, 100.0, 22.0]}},
            {"box": {"id": "obj-livenum-sc-0", "maxclass": "live.numbox", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [600.0, 500.0, 60.0, 22.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [60], "parameter_initial_enable": 1, "parameter_longname": "OedipaScRoot", "parameter_mmax": 127.0, "parameter_mmin": 0.0, "parameter_shortname": "ScRoot", "parameter_type": 1, "parameter_unitstyle": 0, "parameter_visible": 0}}}},
            {"box": {"id": "obj-livenum-sc-1", "maxclass": "live.numbox", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [670.0, 500.0, 60.0, 22.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [64], "parameter_initial_enable": 1, "parameter_longname": "OedipaScThird", "parameter_mmax": 127.0, "parameter_mmin": 0.0, "parameter_shortname": "ScThird", "parameter_type": 1, "parameter_unitstyle": 0, "parameter_visible": 0}}}},
            {"box": {"id": "obj-livenum-sc-2", "maxclass": "live.numbox", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [740.0, 500.0, 60.0, 22.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [67], "parameter_initial_enable": 1, "parameter_longname": "OedipaScFifth", "parameter_mmax": 127.0, "parameter_mmin": 0.0, "parameter_shortname": "ScFifth", "parameter_type": 1, "parameter_unitstyle": 0, "parameter_visible": 0}}}},
            {"box": {"id": "obj-trig-rehydrate", "maxclass": "newobj", "text": "t b b b", "numinlets": 1, "numoutlets": 3, "outlettype": ["bang", "bang", "bang"], "patching_rect": [600.0, 590.0, 70.0, 22.0]}},
            {"box": {"id": "obj-pack-sc", "maxclass": "newobj", "text": "pack 0 0 0", "numinlets": 3, "numoutlets": 1, "outlettype": [""], "patching_rect": [600.0, 620.0, 100.0, 22.0]}},
            {"box": {"id": "obj-prep-startchord", "maxclass": "newobj", "text": "prepend setStartChord", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [600.0, 500.0, 150.0, 22.0]}},

            {"box": {"id": "obj-route-hostready", "maxclass": "newobj", "text": "route hostReady", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [130.0, 760.0, 130.0, 22.0]}},
            {"box": {"id": "obj-trig-hostready", "maxclass": "newobj", "text": "t b", "numinlets": 1, "numoutlets": 1, "outlettype": ["bang"], "patching_rect": [130.0, 790.0, 40.0, 22.0]}},

            {"box": {"id": "obj-route-cellidx", "maxclass": "newobj", "text": "route cellIdx", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [130.0, 820.0, 100.0, 22.0]}},
            {"box": {"id": "obj-eq-cell0", "maxclass": "newobj", "text": "expr $i1 == 0", "numinlets": 1, "numoutlets": 1, "outlettype": ["int"], "patching_rect": [130.0, 850.0, 100.0, 22.0]}},
            {"box": {"id": "obj-eq-cell1", "maxclass": "newobj", "text": "expr $i1 == 1", "numinlets": 1, "numoutlets": 1, "outlettype": ["int"], "patching_rect": [240.0, 850.0, 100.0, 22.0]}},
            {"box": {"id": "obj-eq-cell2", "maxclass": "newobj", "text": "expr $i1 == 2", "numinlets": 1, "numoutlets": 1, "outlettype": ["int"], "patching_rect": [350.0, 850.0, 100.0, 22.0]}},
            {"box": {"id": "obj-eq-cell3", "maxclass": "newobj", "text": "expr $i1 == 3", "numinlets": 1, "numoutlets": 1, "outlettype": ["int"], "patching_rect": [460.0, 850.0, 100.0, 22.0]}},
            {"box": {"id": "obj-led-cell0", "maxclass": "led", "numinlets": 1, "numoutlets": 1, "outlettype": ["int"], "patching_rect": [130.0, 890.0, 24.0, 24.0], "presentation": 1, "presentation_rect": [675.0, 22.0, 12.0, 8.0]}},
            {"box": {"id": "obj-led-cell1", "maxclass": "led", "numinlets": 1, "numoutlets": 1, "outlettype": ["int"], "patching_rect": [240.0, 890.0, 24.0, 24.0], "presentation": 1, "presentation_rect": [799.0, 22.0, 12.0, 8.0]}},
            {"box": {"id": "obj-led-cell2", "maxclass": "led", "numinlets": 1, "numoutlets": 1, "outlettype": ["int"], "patching_rect": [350.0, 890.0, 24.0, 24.0], "presentation": 1, "presentation_rect": [675.0, 52.0, 12.0, 8.0]}},
            {"box": {"id": "obj-led-cell3", "maxclass": "led", "numinlets": 1, "numoutlets": 1, "outlettype": ["int"], "patching_rect": [460.0, 890.0, 24.0, 24.0], "presentation": 1, "presentation_rect": [799.0, 52.0, 12.0, 8.0]}},

            {"box": {"id": "obj-msg-cell0-rest", "maxclass": "message", "text": "setCell 0 rest", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1550.0, 470.0, 110.0, 22.0]}},
            {"box": {"id": "obj-msg-cell1-rest", "maxclass": "message", "text": "setCell 1 rest", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1550.0, 540.0, 110.0, 22.0]}},
            {"box": {"id": "obj-msg-cell2-rest", "maxclass": "message", "text": "setCell 2 rest", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1550.0, 610.0, 110.0, 22.0]}},
            {"box": {"id": "obj-msg-cell3-rest", "maxclass": "message", "text": "setCell 3 rest", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1550.0, 680.0, 110.0, 22.0]}},

            {"box": {"id": "obj-cellfield-comment", "maxclass": "comment", "text": "Cell expression (vel/gate/prob/timing) — Phase 4", "numinlets": 1, "numoutlets": 0, "patching_rect": [970.0, 920.0, 320.0, 20.0]}},

            {"box": {"id": "obj-num-vel-c0", "maxclass": "live.numbox", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [970.0, 950.0, 60.0, 22.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [1.0], "parameter_initial_enable": 1, "parameter_longname": "OedipaCell0Vel", "parameter_mmax": 1.0, "parameter_mmin": 0.0, "parameter_shortname": "C0Vel", "parameter_type": 0, "parameter_unitstyle": 1}}}},
            {"box": {"id": "obj-prep-vel-c0", "maxclass": "newobj", "text": "prepend setCellField 0 velocity", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1040.0, 950.0, 200.0, 22.0]}},
            {"box": {"id": "obj-num-vel-c1", "maxclass": "live.numbox", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [1260.0, 950.0, 60.0, 22.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [1.0], "parameter_initial_enable": 1, "parameter_longname": "OedipaCell1Vel", "parameter_mmax": 1.0, "parameter_mmin": 0.0, "parameter_shortname": "C1Vel", "parameter_type": 0, "parameter_unitstyle": 1}}}},
            {"box": {"id": "obj-prep-vel-c1", "maxclass": "newobj", "text": "prepend setCellField 1 velocity", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1330.0, 950.0, 200.0, 22.0]}},
            {"box": {"id": "obj-num-vel-c2", "maxclass": "live.numbox", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [1550.0, 950.0, 60.0, 22.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [1.0], "parameter_initial_enable": 1, "parameter_longname": "OedipaCell2Vel", "parameter_mmax": 1.0, "parameter_mmin": 0.0, "parameter_shortname": "C2Vel", "parameter_type": 0, "parameter_unitstyle": 1}}}},
            {"box": {"id": "obj-prep-vel-c2", "maxclass": "newobj", "text": "prepend setCellField 2 velocity", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1620.0, 950.0, 200.0, 22.0]}},
            {"box": {"id": "obj-num-vel-c3", "maxclass": "live.numbox", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [1840.0, 950.0, 60.0, 22.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [1.0], "parameter_initial_enable": 1, "parameter_longname": "OedipaCell3Vel", "parameter_mmax": 1.0, "parameter_mmin": 0.0, "parameter_shortname": "C3Vel", "parameter_type": 0, "parameter_unitstyle": 1}}}},
            {"box": {"id": "obj-prep-vel-c3", "maxclass": "newobj", "text": "prepend setCellField 3 velocity", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1910.0, 950.0, 200.0, 22.0]}},

            {"box": {"id": "obj-num-gate-c0", "maxclass": "live.numbox", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [970.0, 980.0, 60.0, 22.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [0.9], "parameter_initial_enable": 1, "parameter_longname": "OedipaCell0Gate", "parameter_mmax": 1.0, "parameter_mmin": 0.0, "parameter_shortname": "C0Gate", "parameter_type": 0, "parameter_unitstyle": 1}}}},
            {"box": {"id": "obj-prep-gate-c0", "maxclass": "newobj", "text": "prepend setCellField 0 gate", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1040.0, 980.0, 200.0, 22.0]}},
            {"box": {"id": "obj-num-gate-c1", "maxclass": "live.numbox", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [1260.0, 980.0, 60.0, 22.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [0.9], "parameter_initial_enable": 1, "parameter_longname": "OedipaCell1Gate", "parameter_mmax": 1.0, "parameter_mmin": 0.0, "parameter_shortname": "C1Gate", "parameter_type": 0, "parameter_unitstyle": 1}}}},
            {"box": {"id": "obj-prep-gate-c1", "maxclass": "newobj", "text": "prepend setCellField 1 gate", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1330.0, 980.0, 200.0, 22.0]}},
            {"box": {"id": "obj-num-gate-c2", "maxclass": "live.numbox", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [1550.0, 980.0, 60.0, 22.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [0.9], "parameter_initial_enable": 1, "parameter_longname": "OedipaCell2Gate", "parameter_mmax": 1.0, "parameter_mmin": 0.0, "parameter_shortname": "C2Gate", "parameter_type": 0, "parameter_unitstyle": 1}}}},
            {"box": {"id": "obj-prep-gate-c2", "maxclass": "newobj", "text": "prepend setCellField 2 gate", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1620.0, 980.0, 200.0, 22.0]}},
            {"box": {"id": "obj-num-gate-c3", "maxclass": "live.numbox", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [1840.0, 980.0, 60.0, 22.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [0.9], "parameter_initial_enable": 1, "parameter_longname": "OedipaCell3Gate", "parameter_mmax": 1.0, "parameter_mmin": 0.0, "parameter_shortname": "C3Gate", "parameter_type": 0, "parameter_unitstyle": 1}}}},
            {"box": {"id": "obj-prep-gate-c3", "maxclass": "newobj", "text": "prepend setCellField 3 gate", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1910.0, 980.0, 200.0, 22.0]}},

            {"box": {"id": "obj-num-prob-c0", "maxclass": "live.numbox", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [970.0, 1010.0, 60.0, 22.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [1.0], "parameter_initial_enable": 1, "parameter_longname": "OedipaCell0Prob", "parameter_mmax": 1.0, "parameter_mmin": 0.0, "parameter_shortname": "C0Prob", "parameter_type": 0, "parameter_unitstyle": 1}}}},
            {"box": {"id": "obj-prep-prob-c0", "maxclass": "newobj", "text": "prepend setCellField 0 probability", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1040.0, 1010.0, 220.0, 22.0]}},
            {"box": {"id": "obj-num-prob-c1", "maxclass": "live.numbox", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [1260.0, 1010.0, 60.0, 22.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [1.0], "parameter_initial_enable": 1, "parameter_longname": "OedipaCell1Prob", "parameter_mmax": 1.0, "parameter_mmin": 0.0, "parameter_shortname": "C1Prob", "parameter_type": 0, "parameter_unitstyle": 1}}}},
            {"box": {"id": "obj-prep-prob-c1", "maxclass": "newobj", "text": "prepend setCellField 1 probability", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1330.0, 1010.0, 220.0, 22.0]}},
            {"box": {"id": "obj-num-prob-c2", "maxclass": "live.numbox", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [1550.0, 1010.0, 60.0, 22.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [1.0], "parameter_initial_enable": 1, "parameter_longname": "OedipaCell2Prob", "parameter_mmax": 1.0, "parameter_mmin": 0.0, "parameter_shortname": "C2Prob", "parameter_type": 0, "parameter_unitstyle": 1}}}},
            {"box": {"id": "obj-prep-prob-c2", "maxclass": "newobj", "text": "prepend setCellField 2 probability", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1620.0, 1010.0, 220.0, 22.0]}},
            {"box": {"id": "obj-num-prob-c3", "maxclass": "live.numbox", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [1840.0, 1010.0, 60.0, 22.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [1.0], "parameter_initial_enable": 1, "parameter_longname": "OedipaCell3Prob", "parameter_mmax": 1.0, "parameter_mmin": 0.0, "parameter_shortname": "C3Prob", "parameter_type": 0, "parameter_unitstyle": 1}}}},
            {"box": {"id": "obj-prep-prob-c3", "maxclass": "newobj", "text": "prepend setCellField 3 probability", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1910.0, 1010.0, 220.0, 22.0]}},

            {"box": {"id": "obj-num-time-c0", "maxclass": "live.numbox", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [970.0, 1040.0, 60.0, 22.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [0.0], "parameter_initial_enable": 1, "parameter_longname": "OedipaCell0Time", "parameter_mmax": 0.5, "parameter_mmin": -0.5, "parameter_shortname": "C0Time", "parameter_type": 0, "parameter_unitstyle": 1}}}},
            {"box": {"id": "obj-prep-time-c0", "maxclass": "newobj", "text": "prepend setCellField 0 timing", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1040.0, 1040.0, 200.0, 22.0]}},
            {"box": {"id": "obj-num-time-c1", "maxclass": "live.numbox", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [1260.0, 1040.0, 60.0, 22.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [0.0], "parameter_initial_enable": 1, "parameter_longname": "OedipaCell1Time", "parameter_mmax": 0.5, "parameter_mmin": -0.5, "parameter_shortname": "C1Time", "parameter_type": 0, "parameter_unitstyle": 1}}}},
            {"box": {"id": "obj-prep-time-c1", "maxclass": "newobj", "text": "prepend setCellField 1 timing", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1330.0, 1040.0, 200.0, 22.0]}},
            {"box": {"id": "obj-num-time-c2", "maxclass": "live.numbox", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [1550.0, 1040.0, 60.0, 22.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [0.0], "parameter_initial_enable": 1, "parameter_longname": "OedipaCell2Time", "parameter_mmax": 0.5, "parameter_mmin": -0.5, "parameter_shortname": "C2Time", "parameter_type": 0, "parameter_unitstyle": 1}}}},
            {"box": {"id": "obj-prep-time-c2", "maxclass": "newobj", "text": "prepend setCellField 2 timing", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1620.0, 1040.0, 200.0, 22.0]}},
            {"box": {"id": "obj-num-time-c3", "maxclass": "live.numbox", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [1840.0, 1040.0, 60.0, 22.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [0.0], "parameter_initial_enable": 1, "parameter_longname": "OedipaCell3Time", "parameter_mmax": 0.5, "parameter_mmin": -0.5, "parameter_shortname": "C3Time", "parameter_type": 0, "parameter_unitstyle": 1}}}},
            {"box": {"id": "obj-prep-time-c3", "maxclass": "newobj", "text": "prepend setCellField 3 timing", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1910.0, 1040.0, 200.0, 22.0]}},

            {"box": {"id": "obj-global-comment", "maxclass": "comment", "text": "Global rhythmic layer — Phase 4", "numinlets": 1, "numoutlets": 0, "patching_rect": [970.0, 1080.0, 320.0, 20.0]}},

            {"box": {"id": "obj-swing", "maxclass": "live.dial", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [970.0, 1110.0, 60.0, 40.0], "presentation": 1, "presentation_rect": [878.0, 24.0, 38.0, 38.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [0.5], "parameter_initial_enable": 1, "parameter_longname": "OedipaSwing", "parameter_mmax": 0.75, "parameter_mmin": 0.5, "parameter_shortname": "Swing", "parameter_type": 0, "parameter_unitstyle": 1}}}},
            {"box": {"id": "obj-prep-swing", "maxclass": "newobj", "text": "prepend setParams swing", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1040.0, 1110.0, 170.0, 22.0]}},

            {"box": {"id": "obj-subdivision", "maxclass": "live.tab", "numinlets": 1, "numoutlets": 3, "outlettype": ["", "", "float"], "parameter_enable": 1, "patching_rect": [970.0, 1170.0, 130.0, 22.0], "presentation": 1, "presentation_rect": [928.0, 24.0, 100.0, 18.0], "saved_attribute_attributes": {"valueof": {"parameter_enum": ["8", "16", "32", "8T", "16T"], "parameter_initial": [1], "parameter_initial_enable": 1, "parameter_longname": "OedipaSubdivision", "parameter_shortname": "Subdiv", "parameter_type": 2}}}},
            {"box": {"id": "obj-sel-subdivision", "maxclass": "newobj", "text": "sel 0 1 2 3 4", "numinlets": 1, "numoutlets": 6, "outlettype": ["bang", "bang", "bang", "bang", "bang", ""], "patching_rect": [1110.0, 1170.0, 90.0, 22.0]}},
            {"box": {"id": "obj-msg-subdiv-8", "maxclass": "message", "text": "setParams ticksPerStep 12", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1110.0, 1200.0, 200.0, 22.0]}},
            {"box": {"id": "obj-msg-subdiv-16", "maxclass": "message", "text": "setParams ticksPerStep 6", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1110.0, 1230.0, 200.0, 22.0]}},
            {"box": {"id": "obj-msg-subdiv-32", "maxclass": "message", "text": "setParams ticksPerStep 3", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1110.0, 1260.0, 200.0, 22.0]}},
            {"box": {"id": "obj-msg-subdiv-8T", "maxclass": "message", "text": "setParams ticksPerStep 8", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1110.0, 1290.0, 200.0, 22.0]}},
            {"box": {"id": "obj-msg-subdiv-16T", "maxclass": "message", "text": "setParams ticksPerStep 4", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1110.0, 1320.0, 200.0, 22.0]}},

            {"box": {"id": "obj-stepdir", "maxclass": "live.tab", "numinlets": 1, "numoutlets": 3, "outlettype": ["", "", "float"], "parameter_enable": 1, "patching_rect": [970.0, 1370.0, 200.0, 22.0], "presentation": 1, "presentation_rect": [928.0, 64.0, 100.0, 18.0], "saved_attribute_attributes": {"valueof": {"parameter_enum": ["Fwd", "Rev", "PPng", "Rnd"], "parameter_initial": [0], "parameter_initial_enable": 1, "parameter_longname": "OedipaStepDirection", "parameter_shortname": "StepDir", "parameter_type": 2}}}},
            {"box": {"id": "obj-sel-stepdir", "maxclass": "newobj", "text": "sel 0 1 2 3", "numinlets": 1, "numoutlets": 5, "outlettype": ["bang", "bang", "bang", "bang", ""], "patching_rect": [1180.0, 1370.0, 80.0, 22.0]}},
            {"box": {"id": "obj-msg-stepdir-fwd", "maxclass": "message", "text": "setParams stepDirection forward", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1180.0, 1400.0, 230.0, 22.0]}},
            {"box": {"id": "obj-msg-stepdir-rev", "maxclass": "message", "text": "setParams stepDirection reverse", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1180.0, 1430.0, 230.0, 22.0]}},
            {"box": {"id": "obj-msg-stepdir-pp", "maxclass": "message", "text": "setParams stepDirection pingpong", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1180.0, 1460.0, 230.0, 22.0]}},
            {"box": {"id": "obj-msg-stepdir-rnd", "maxclass": "message", "text": "setParams stepDirection random", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1180.0, 1490.0, 230.0, 22.0]}},

            {"box": {"id": "obj-humvel", "maxclass": "live.dial", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [970.0, 1540.0, 60.0, 40.0], "presentation": 1, "presentation_rect": [878.0, 104.0, 38.0, 38.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [0.0], "parameter_initial_enable": 1, "parameter_longname": "OedipaHumanizeVelocity", "parameter_mmax": 1.0, "parameter_mmin": 0.0, "parameter_shortname": "Vel", "parameter_type": 0, "parameter_unitstyle": 1}}}},
            {"box": {"id": "obj-prep-humvel", "maxclass": "newobj", "text": "prepend setParams humanizeVelocity", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1040.0, 1540.0, 240.0, 22.0]}},

            {"box": {"id": "obj-humgate", "maxclass": "live.dial", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [970.0, 1600.0, 60.0, 40.0], "presentation": 1, "presentation_rect": [922.0, 104.0, 38.0, 38.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [0.0], "parameter_initial_enable": 1, "parameter_longname": "OedipaHumanizeGate", "parameter_mmax": 1.0, "parameter_mmin": 0.0, "parameter_shortname": "Gate", "parameter_type": 0, "parameter_unitstyle": 1}}}},
            {"box": {"id": "obj-prep-humgate", "maxclass": "newobj", "text": "prepend setParams humanizeGate", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1040.0, 1600.0, 240.0, 22.0]}},

            {"box": {"id": "obj-humtime", "maxclass": "live.dial", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [970.0, 1660.0, 60.0, 40.0], "presentation": 1, "presentation_rect": [966.0, 104.0, 38.0, 38.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [0.0], "parameter_initial_enable": 1, "parameter_longname": "OedipaHumanizeTiming", "parameter_mmax": 1.0, "parameter_mmin": 0.0, "parameter_shortname": "Tim", "parameter_type": 0, "parameter_unitstyle": 1}}}},
            {"box": {"id": "obj-prep-humtime", "maxclass": "newobj", "text": "prepend setParams humanizeTiming", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1040.0, 1660.0, 240.0, 22.0]}},

            {"box": {"id": "obj-jsui-separator3", "maxclass": "jsui", "filename": "/Users/tn/src/vst/oedipa/m4l/separator-renderer.js", "border": 0, "numinlets": 1, "numoutlets": 0, "patching_rect": [970.0, 1780.0, 1.0, 172.0], "presentation": 1, "presentation_rect": [869.0, 8.0, 1.0, 172.0]}},

            {"box": {"id": "obj-lbl-feel-swing", "maxclass": "comment", "text": "Swing", "numinlets": 1, "numoutlets": 0, "fontsize": 9.0, "patching_rect": [1300.0, 1110.0, 60.0, 16.0], "presentation": 1, "presentation_rect": [878.0, 8.0, 38.0, 14.0]}},
            {"box": {"id": "obj-lbl-feel-subdiv", "maxclass": "comment", "text": "Subdiv", "numinlets": 1, "numoutlets": 0, "fontsize": 9.0, "patching_rect": [1300.0, 1170.0, 60.0, 16.0], "presentation": 1, "presentation_rect": [928.0, 8.0, 100.0, 14.0]}},
            {"box": {"id": "obj-lbl-feel-stepdir", "maxclass": "comment", "text": "Step Dir", "numinlets": 1, "numoutlets": 0, "fontsize": 9.0, "patching_rect": [1300.0, 1370.0, 60.0, 16.0], "presentation": 1, "presentation_rect": [928.0, 48.0, 100.0, 14.0]}},
            {"box": {"id": "obj-lbl-feel-humanize", "maxclass": "comment", "text": "Humanize", "numinlets": 1, "numoutlets": 0, "fontsize": 9.0, "patching_rect": [1300.0, 1530.0, 60.0, 16.0], "presentation": 1, "presentation_rect": [878.0, 88.0, 170.0, 14.0]}},
            {"box": {"id": "obj-humprob", "maxclass": "live.dial", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "parameter_enable": 1, "patching_rect": [970.0, 1720.0, 60.0, 40.0], "presentation": 1, "presentation_rect": [1010.0, 104.0, 38.0, 38.0], "saved_attribute_attributes": {"valueof": {"parameter_initial": [0.0], "parameter_initial_enable": 1, "parameter_longname": "OedipaHumanizeProbability", "parameter_mmax": 1.0, "parameter_mmin": 0.0, "parameter_shortname": "Prob", "parameter_type": 0, "parameter_unitstyle": 1}}}},
            {"box": {"id": "obj-prep-humprob", "maxclass": "newobj", "text": "prepend setParams humanizeProbability", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [1040.0, 1720.0, 270.0, 22.0]}}
        ],
        "lines": [
            {"patchline": {"source": ["obj-midiin", 0], "destination": ["obj-midiout", 0]}},

            {"patchline": {"source": ["obj-thisdevice", 0], "destination": ["obj-print-thisdev", 0]}},
            {"patchline": {"source": ["obj-thisdevice", 0], "destination": ["obj-getid-msg", 0]}},
            {"patchline": {"source": ["obj-loadbang", 0], "destination": ["obj-getid-msg", 0]}},
            {"patchline": {"source": ["obj-debug-bang", 0], "destination": ["obj-getid-msg", 0]}},
            {"patchline": {"source": ["obj-getid-msg", 0], "destination": ["obj-livepath", 0]}},
            {"patchline": {"source": ["obj-livepath", 0], "destination": ["obj-liveobserver", 0]}},
            {"patchline": {"source": ["obj-livepath", 0], "destination": ["obj-print-lp", 0]}},
            {"patchline": {"source": ["obj-liveobserver", 0], "destination": ["obj-print-lo", 0]}},
            {"patchline": {"source": ["obj-liveobserver", 0], "destination": ["obj-metro", 0]}},
            {"patchline": {"source": ["obj-liveobserver", 0], "destination": ["obj-sel-stop", 0]}},
            {"patchline": {"source": ["obj-sel-stop", 0], "destination": ["obj-panic-msg", 0]}},

            {"patchline": {"source": ["obj-metro", 0], "destination": ["obj-counter", 0]}},
            {"patchline": {"source": ["obj-metro", 0], "destination": ["obj-print-metro", 0]}},
            {"patchline": {"source": ["obj-test-bang", 0], "destination": ["obj-counter", 0]}},
            {"patchline": {"source": ["obj-counter", 0], "destination": ["obj-prepend-step", 0]}},
            {"patchline": {"source": ["obj-prepend-step", 0], "destination": ["obj-nodescript", 0]}},

            {"patchline": {"source": ["obj-panic-bang", 0], "destination": ["obj-panic-msg", 0]}},
            {"patchline": {"source": ["obj-panic-msg", 0], "destination": ["obj-nodescript", 0]}},

            {"patchline": {"source": ["obj-nodescript", 0], "destination": ["obj-print", 0]}},
            {"patchline": {"source": ["obj-nodescript", 0], "destination": ["obj-route", 0]}},

            {"patchline": {"source": ["obj-route", 0], "destination": ["obj-unpack", 0]}},
            {"patchline": {"source": ["obj-unpack", 0], "destination": ["obj-pack", 0]}},
            {"patchline": {"source": ["obj-unpack", 1], "destination": ["obj-pack", 1]}},
            {"patchline": {"source": ["obj-pack", 0], "destination": ["obj-midiformat", 0]}},
            {"patchline": {"source": ["obj-midiformat", 0], "destination": ["obj-midiout", 0]}},

            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-stepsper", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-msg-getvalueof-seventh", 0]}},
            {"patchline": {"source": ["obj-msg-getvalueof-seventh", 0], "destination": ["obj-seventh", 0]}},
            {"patchline": {"source": ["obj-seventh", 1], "destination": ["obj-prep-seventh", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-channel", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-voicing", 0]}},

            {"patchline": {"source": ["obj-stepsper", 0], "destination": ["obj-prep-stepsper", 0]}},
            {"patchline": {"source": ["obj-prep-stepsper", 0], "destination": ["obj-nodescript", 0]}},

            {"patchline": {"source": ["obj-seventh", 0], "destination": ["obj-prep-seventh", 0]}},
            {"patchline": {"source": ["obj-prep-seventh", 0], "destination": ["obj-nodescript", 0]}},

            {"patchline": {"source": ["obj-channel", 0], "destination": ["obj-prep-channel", 0]}},
            {"patchline": {"source": ["obj-prep-channel", 0], "destination": ["obj-nodescript", 0]}},

            {"patchline": {"source": ["obj-voicing", 0], "destination": ["obj-sel-voicing", 0]}},
            {"patchline": {"source": ["obj-sel-voicing", 0], "destination": ["obj-msg-voicing-close", 0]}},
            {"patchline": {"source": ["obj-sel-voicing", 1], "destination": ["obj-msg-voicing-spread", 0]}},
            {"patchline": {"source": ["obj-sel-voicing", 2], "destination": ["obj-msg-voicing-drop2", 0]}},
            {"patchline": {"source": ["obj-msg-voicing-close", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-msg-voicing-spread", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-msg-voicing-drop2", 0], "destination": ["obj-nodescript", 0]}},

            {"patchline": {"source": ["obj-route", 1], "destination": ["obj-route-cellidx", 0]}},
            {"patchline": {"source": ["obj-route-cellidx", 1], "destination": ["obj-route-hostready", 0]}},
            {"patchline": {"source": ["obj-route-hostready", 0], "destination": ["obj-trig-hostready", 0]}},
            {"patchline": {"source": ["obj-route-hostready", 1], "destination": ["obj-route-lattice", 0]}},
            {"patchline": {"source": ["obj-route-cellidx", 0], "destination": ["obj-eq-cell0", 0]}},
            {"patchline": {"source": ["obj-route-cellidx", 0], "destination": ["obj-eq-cell1", 0]}},
            {"patchline": {"source": ["obj-route-cellidx", 0], "destination": ["obj-eq-cell2", 0]}},
            {"patchline": {"source": ["obj-route-cellidx", 0], "destination": ["obj-eq-cell3", 0]}},
            {"patchline": {"source": ["obj-eq-cell0", 0], "destination": ["obj-led-cell0", 0]}},
            {"patchline": {"source": ["obj-eq-cell1", 0], "destination": ["obj-led-cell1", 0]}},
            {"patchline": {"source": ["obj-eq-cell2", 0], "destination": ["obj-led-cell2", 0]}},
            {"patchline": {"source": ["obj-eq-cell3", 0], "destination": ["obj-led-cell3", 0]}},
            {"patchline": {"source": ["obj-route-lattice", 0], "destination": ["obj-prep-lcenter", 0]}},
            {"patchline": {"source": ["obj-route-lattice", 1], "destination": ["obj-prep-lcurrent", 0]}},
            {"patchline": {"source": ["obj-route-lattice", 2], "destination": ["obj-msg-lclear", 0]}},
            {"patchline": {"source": ["obj-prep-lcenter", 0], "destination": ["obj-jsui", 0]}},
            {"patchline": {"source": ["obj-prep-lcurrent", 0], "destination": ["obj-jsui", 0]}},
            {"patchline": {"source": ["obj-msg-lclear", 0], "destination": ["obj-jsui", 0]}},
            {"patchline": {"source": ["obj-jsui", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-jsui", 0], "destination": ["obj-route-startchord", 0]}},
            {"patchline": {"source": ["obj-route-startchord", 0], "destination": ["obj-unpack-sc", 0]}},
            {"patchline": {"source": ["obj-unpack-sc", 0], "destination": ["obj-livenum-sc-0", 0]}},
            {"patchline": {"source": ["obj-unpack-sc", 1], "destination": ["obj-livenum-sc-1", 0]}},
            {"patchline": {"source": ["obj-unpack-sc", 2], "destination": ["obj-livenum-sc-2", 0]}},
            {"patchline": {"source": ["obj-trig-rehydrate", 2], "destination": ["obj-livenum-sc-2", 0]}},
            {"patchline": {"source": ["obj-trig-rehydrate", 1], "destination": ["obj-livenum-sc-1", 0]}},
            {"patchline": {"source": ["obj-trig-rehydrate", 0], "destination": ["obj-livenum-sc-0", 0]}},
            {"patchline": {"source": ["obj-livenum-sc-2", 0], "destination": ["obj-pack-sc", 2]}},
            {"patchline": {"source": ["obj-livenum-sc-1", 0], "destination": ["obj-pack-sc", 1]}},
            {"patchline": {"source": ["obj-livenum-sc-0", 0], "destination": ["obj-pack-sc", 0]}},
            {"patchline": {"source": ["obj-pack-sc", 0], "destination": ["obj-prep-startchord", 0]}},
            {"patchline": {"source": ["obj-prep-startchord", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-trig-rehydrate", 0]}},

            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-msg-refresh", 0]}},
            {"patchline": {"source": ["obj-msg-refresh", 0], "destination": ["obj-nodescript", 0]}},

            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-cell0", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-cell1", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-cell2", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-cell3", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-jitter", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-seed", 0]}},

            {"patchline": {"source": ["obj-cell0", 0], "destination": ["obj-sel-cell0", 0]}},
            {"patchline": {"source": ["obj-sel-cell0", 0], "destination": ["obj-msg-cell0-P", 0]}},
            {"patchline": {"source": ["obj-sel-cell0", 1], "destination": ["obj-msg-cell0-L", 0]}},
            {"patchline": {"source": ["obj-sel-cell0", 2], "destination": ["obj-msg-cell0-R", 0]}},
            {"patchline": {"source": ["obj-sel-cell0", 3], "destination": ["obj-msg-cell0-H", 0]}},
            {"patchline": {"source": ["obj-msg-cell0-P", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-msg-cell0-L", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-msg-cell0-R", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-msg-cell0-H", 0], "destination": ["obj-nodescript", 0]}},

            {"patchline": {"source": ["obj-cell1", 0], "destination": ["obj-sel-cell1", 0]}},
            {"patchline": {"source": ["obj-sel-cell1", 0], "destination": ["obj-msg-cell1-P", 0]}},
            {"patchline": {"source": ["obj-sel-cell1", 1], "destination": ["obj-msg-cell1-L", 0]}},
            {"patchline": {"source": ["obj-sel-cell1", 2], "destination": ["obj-msg-cell1-R", 0]}},
            {"patchline": {"source": ["obj-sel-cell1", 3], "destination": ["obj-msg-cell1-H", 0]}},
            {"patchline": {"source": ["obj-msg-cell1-P", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-msg-cell1-L", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-msg-cell1-R", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-msg-cell1-H", 0], "destination": ["obj-nodescript", 0]}},

            {"patchline": {"source": ["obj-cell2", 0], "destination": ["obj-sel-cell2", 0]}},
            {"patchline": {"source": ["obj-sel-cell2", 0], "destination": ["obj-msg-cell2-P", 0]}},
            {"patchline": {"source": ["obj-sel-cell2", 1], "destination": ["obj-msg-cell2-L", 0]}},
            {"patchline": {"source": ["obj-sel-cell2", 2], "destination": ["obj-msg-cell2-R", 0]}},
            {"patchline": {"source": ["obj-sel-cell2", 3], "destination": ["obj-msg-cell2-H", 0]}},
            {"patchline": {"source": ["obj-msg-cell2-P", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-msg-cell2-L", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-msg-cell2-R", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-msg-cell2-H", 0], "destination": ["obj-nodescript", 0]}},

            {"patchline": {"source": ["obj-cell3", 0], "destination": ["obj-sel-cell3", 0]}},
            {"patchline": {"source": ["obj-sel-cell3", 0], "destination": ["obj-msg-cell3-P", 0]}},
            {"patchline": {"source": ["obj-sel-cell3", 1], "destination": ["obj-msg-cell3-L", 0]}},
            {"patchline": {"source": ["obj-sel-cell3", 2], "destination": ["obj-msg-cell3-R", 0]}},
            {"patchline": {"source": ["obj-sel-cell3", 3], "destination": ["obj-msg-cell3-H", 0]}},
            {"patchline": {"source": ["obj-msg-cell3-P", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-msg-cell3-L", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-msg-cell3-R", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-msg-cell3-H", 0], "destination": ["obj-nodescript", 0]}},

            {"patchline": {"source": ["obj-jitter", 0], "destination": ["obj-prep-jitter", 0]}},
            {"patchline": {"source": ["obj-prep-jitter", 0], "destination": ["obj-nodescript", 0]}},

            {"patchline": {"source": ["obj-seed", 0], "destination": ["obj-prep-seed", 0]}},
            {"patchline": {"source": ["obj-prep-seed", 0], "destination": ["obj-nodescript", 0]}},

            {"patchline": {"source": ["obj-midiin", 0], "destination": ["obj-midiparse", 0]}},
            {"patchline": {"source": ["obj-midiparse", 0], "destination": ["obj-unpack-note-in", 0]}},
            {"patchline": {"source": ["obj-midiparse", 6], "destination": ["obj-if-noteinout", 2]}},
            {"patchline": {"source": ["obj-unpack-note-in", 1], "destination": ["obj-if-noteinout", 1]}},
            {"patchline": {"source": ["obj-unpack-note-in", 0], "destination": ["obj-if-noteinout", 0]}},
            {"patchline": {"source": ["obj-if-noteinout", 0], "destination": ["obj-nodescript", 0]}},

            {"patchline": {"source": ["obj-sel-stop", 1], "destination": ["obj-msg-transportstart", 0]}},
            {"patchline": {"source": ["obj-msg-transportstart", 0], "destination": ["obj-nodescript", 0]}},

            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-msg-getvalueof-trig", 0]}},
            {"patchline": {"source": ["obj-msg-getvalueof-trig", 0], "destination": ["obj-triggermode", 0]}},
            {"patchline": {"source": ["obj-triggermode", 1], "destination": ["obj-prep-triggermode", 0]}},
            {"patchline": {"source": ["obj-triggermode", 0], "destination": ["obj-prep-triggermode", 0]}},
            {"patchline": {"source": ["obj-prep-triggermode", 0], "destination": ["obj-nodescript", 0]}},

            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-inputchannel", 0]}},
            {"patchline": {"source": ["obj-inputchannel", 0], "destination": ["obj-prep-inputchannel", 0]}},
            {"patchline": {"source": ["obj-prep-inputchannel", 0], "destination": ["obj-nodescript", 0]}},

            {"patchline": {"source": ["obj-sel-cell0", 4], "destination": ["obj-msg-cell0-rest", 0]}},
            {"patchline": {"source": ["obj-sel-cell1", 4], "destination": ["obj-msg-cell1-rest", 0]}},
            {"patchline": {"source": ["obj-sel-cell2", 4], "destination": ["obj-msg-cell2-rest", 0]}},
            {"patchline": {"source": ["obj-sel-cell3", 4], "destination": ["obj-msg-cell3-rest", 0]}},
            {"patchline": {"source": ["obj-msg-cell0-rest", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-msg-cell1-rest", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-msg-cell2-rest", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-msg-cell3-rest", 0], "destination": ["obj-nodescript", 0]}},

            {"patchline": {"source": ["obj-num-vel-c0", 0], "destination": ["obj-prep-vel-c0", 0]}},
            {"patchline": {"source": ["obj-prep-vel-c0", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-num-vel-c1", 0], "destination": ["obj-prep-vel-c1", 0]}},
            {"patchline": {"source": ["obj-prep-vel-c1", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-num-vel-c2", 0], "destination": ["obj-prep-vel-c2", 0]}},
            {"patchline": {"source": ["obj-prep-vel-c2", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-num-vel-c3", 0], "destination": ["obj-prep-vel-c3", 0]}},
            {"patchline": {"source": ["obj-prep-vel-c3", 0], "destination": ["obj-nodescript", 0]}},

            {"patchline": {"source": ["obj-num-gate-c0", 0], "destination": ["obj-prep-gate-c0", 0]}},
            {"patchline": {"source": ["obj-prep-gate-c0", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-num-gate-c1", 0], "destination": ["obj-prep-gate-c1", 0]}},
            {"patchline": {"source": ["obj-prep-gate-c1", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-num-gate-c2", 0], "destination": ["obj-prep-gate-c2", 0]}},
            {"patchline": {"source": ["obj-prep-gate-c2", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-num-gate-c3", 0], "destination": ["obj-prep-gate-c3", 0]}},
            {"patchline": {"source": ["obj-prep-gate-c3", 0], "destination": ["obj-nodescript", 0]}},

            {"patchline": {"source": ["obj-num-prob-c0", 0], "destination": ["obj-prep-prob-c0", 0]}},
            {"patchline": {"source": ["obj-prep-prob-c0", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-num-prob-c1", 0], "destination": ["obj-prep-prob-c1", 0]}},
            {"patchline": {"source": ["obj-prep-prob-c1", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-num-prob-c2", 0], "destination": ["obj-prep-prob-c2", 0]}},
            {"patchline": {"source": ["obj-prep-prob-c2", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-num-prob-c3", 0], "destination": ["obj-prep-prob-c3", 0]}},
            {"patchline": {"source": ["obj-prep-prob-c3", 0], "destination": ["obj-nodescript", 0]}},

            {"patchline": {"source": ["obj-num-time-c0", 0], "destination": ["obj-prep-time-c0", 0]}},
            {"patchline": {"source": ["obj-prep-time-c0", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-num-time-c1", 0], "destination": ["obj-prep-time-c1", 0]}},
            {"patchline": {"source": ["obj-prep-time-c1", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-num-time-c2", 0], "destination": ["obj-prep-time-c2", 0]}},
            {"patchline": {"source": ["obj-prep-time-c2", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-num-time-c3", 0], "destination": ["obj-prep-time-c3", 0]}},
            {"patchline": {"source": ["obj-prep-time-c3", 0], "destination": ["obj-nodescript", 0]}},

            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-num-vel-c0", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-num-vel-c1", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-num-vel-c2", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-num-vel-c3", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-num-gate-c0", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-num-gate-c1", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-num-gate-c2", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-num-gate-c3", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-num-prob-c0", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-num-prob-c1", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-num-prob-c2", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-num-prob-c3", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-num-time-c0", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-num-time-c1", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-num-time-c2", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-num-time-c3", 0]}},

            {"patchline": {"source": ["obj-swing", 0], "destination": ["obj-prep-swing", 0]}},
            {"patchline": {"source": ["obj-prep-swing", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-swing", 0]}},

            {"patchline": {"source": ["obj-subdivision", 0], "destination": ["obj-sel-subdivision", 0]}},
            {"patchline": {"source": ["obj-sel-subdivision", 0], "destination": ["obj-msg-subdiv-8", 0]}},
            {"patchline": {"source": ["obj-sel-subdivision", 1], "destination": ["obj-msg-subdiv-16", 0]}},
            {"patchline": {"source": ["obj-sel-subdivision", 2], "destination": ["obj-msg-subdiv-32", 0]}},
            {"patchline": {"source": ["obj-sel-subdivision", 3], "destination": ["obj-msg-subdiv-8T", 0]}},
            {"patchline": {"source": ["obj-sel-subdivision", 4], "destination": ["obj-msg-subdiv-16T", 0]}},
            {"patchline": {"source": ["obj-msg-subdiv-8", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-msg-subdiv-16", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-msg-subdiv-32", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-msg-subdiv-8T", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-msg-subdiv-16T", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-subdivision", 0]}},

            {"patchline": {"source": ["obj-stepdir", 0], "destination": ["obj-sel-stepdir", 0]}},
            {"patchline": {"source": ["obj-sel-stepdir", 0], "destination": ["obj-msg-stepdir-fwd", 0]}},
            {"patchline": {"source": ["obj-sel-stepdir", 1], "destination": ["obj-msg-stepdir-rev", 0]}},
            {"patchline": {"source": ["obj-sel-stepdir", 2], "destination": ["obj-msg-stepdir-pp", 0]}},
            {"patchline": {"source": ["obj-sel-stepdir", 3], "destination": ["obj-msg-stepdir-rnd", 0]}},
            {"patchline": {"source": ["obj-msg-stepdir-fwd", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-msg-stepdir-rev", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-msg-stepdir-pp", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-msg-stepdir-rnd", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-stepdir", 0]}},

            {"patchline": {"source": ["obj-humvel", 0], "destination": ["obj-prep-humvel", 0]}},
            {"patchline": {"source": ["obj-prep-humvel", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-humvel", 0]}},

            {"patchline": {"source": ["obj-humgate", 0], "destination": ["obj-prep-humgate", 0]}},
            {"patchline": {"source": ["obj-prep-humgate", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-humgate", 0]}},

            {"patchline": {"source": ["obj-humtime", 0], "destination": ["obj-prep-humtime", 0]}},
            {"patchline": {"source": ["obj-prep-humtime", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-humtime", 0]}},

            {"patchline": {"source": ["obj-humprob", 0], "destination": ["obj-prep-humprob", 0]}},
            {"patchline": {"source": ["obj-prep-humprob", 0], "destination": ["obj-nodescript", 0]}},
            {"patchline": {"source": ["obj-trig-hostready", 0], "destination": ["obj-humprob", 0]}}
        ]
    }
}
